global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dummy_service'
    static_configs:
      - targets: ['dummy_service:8000']
    metrics_path: '/metrics'

  - job_name: 'ai_analyzer'
    static_configs:
      - targets: ['ai_analyzer:8001']
    metrics_path: '/metrics'
